apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-app-deploy
  labels:
    app: healthcare-app-deploy-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcare-app
  template:
    metadata:
      labels:
        app: healthcare-app
    spec:
      containers:
      - name: healthcare-app-container
        image: sweta912sharma/healthcare-app  # Replace with your actual image name
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-app-np-service
  labels:
    app: healthcare-app
spec:
  selector:
    app: healthcare-app
  type: NodePort
  ports:
  - nodePort: 31082   # NodePort exposed outside the cluster
    port: 8080        # Service port (what clients use inside the cluster)
    targetPort: 8082  # Container port
